//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tesuri.DevToys.XPathTester {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XPathTester {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XPathTester() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tesuri.DevToys.XPathTester.XPathTester", typeof(XPathTester).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   XPath Tester Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClipboardCopyButtonTitle {
            get {
                return ResourceManager.GetString("ClipboardCopyButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test a XPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputXPathTitle {
            get {
                return ResourceManager.GetString("InputXPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XPath Tester に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputError {
            get {
                return ResourceManager.GetString("OutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputResult {
            get {
                return ResourceManager.GetString("OutputResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   path xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim spases/newline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StyleSettingsTrimTitle {
            get {
                return ResourceManager.GetString("StyleSettingsTrimTitle", resourceCulture);
            }
        }
    }
}
